name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - uses: actions/checkout@v2

      - name: Run script
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

          api_branch="API"
          blazorapp_branch="BlazorApp"

          # Function to split changes into a subproject branch
          split_changes() {
            dir=$1
            branch=$2

            # Check if the branch already exists
            if git rev-parse --verify $branch >/dev/null 2>&1; then
                # If the branch exists, delete it
                git branch -D $branch
            fi

            # Create a new branch from the current one
            git checkout -b $branch

            # Add the directory to the new branch and commit
            git add $dir
            git commit -m "Initial commit for $branch"
             }

          # Call the function for each subproject
          split_changes 'API' $api_branch
          split_changes 'BlazorApp' $blazorapp_branch

          git push --force origin $api_branch
          git push --force origin $blazorapp_branch
