name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - uses: actions/checkout@v2

      - name: Run script
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

          api_branch="API"
          blazorapp_branch="BlazorApp"

          # Function to split changes into a subproject branch
          split_changes() {
            dir=$1
            branch=$2

            # Check if branch exists and if it does, delete it
            if git show-ref --verify --quiet refs/heads/$branch; then
              git branch -D $branch
            fi

            # Create a new branch from an empty commit
            git checkout --orphan $branch
            git rm -rf .
            git clean -fdx
            git commit --allow-empty -m "Initial empty commit"

            # Filter the branch to only include the subproject directory
            git filter-branch -f --subdirectory-filter $dir -- --all
          }

          # Call the function for each subproject
          split_changes 'API' $api_branch
          split_changes 'BlazorApp' $blazorapp_branch

          git push --force origin $api_branch
          git push --force origin $blazorapp_branch
