name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "20"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Run script
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

          api_branch="API"
          blazorapp_branch="BlazorApp"

          # Function to copy directory to a new branch
          copy_to_branch() {
            dir=$1
            branch=$2
            dirToRemove=$3

            # Delete the branch if it exists, both locally and remotely
            git branch -D $branch || true
            git push origin --delete $branch || true

            # Create a new branch from the current branch and switch to it
            git checkout -b $branch

            # Check if the to remove directory exists
            if [ -d "$dirToRemove" ]; then
                # If the BlazorApp directory exists, remove it
                rm -rf $dirToRemove
                # Stage the changes
                git add .
            fi

            # If there are no changes to commit, print a message
            if git diff --quiet && git diff --staged --quiet; then
                echo "No changes to commit"
            else
                # If there are changes to commit, make a commit
                git commit -m "Git Actions Update To $branch"
            fi

            # Push the branch to the remote repository
             git push --force https://$PAT@github.com/boop-bap/JokeManagerMonoRepo.git $branch
             }

            # Call the function for each directory
            copy_to_branch 'API' $api_branch 'BlazorApp'
            copy_to_branch 'BlazorApp' $blazorapp_branch 'API'
