name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Run script
        env:
          PAT: ${{ secrets.PAT }}

        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

          api_branch="API"
          blazorapp_branch="BlazorApp"

          # Function to copy directory to a new branch
          copy_to_branch() {
            dir=$1
            branch=$2

            # Check if the branch already exists
            if git rev-parse --verify $branch >/dev/null 2>&1; then
              # If the branch exists, delete it
              git branch -D $branch
            fi

            # Create a new branch from the current one
            git checkout -b $branch

            # Add the directory to the new branch
            git add $dir

            # Check if there are changes to commit
            if git diff-index --quiet HEAD --; then
              # If there are no changes to commit, do nothing
              echo "No changes to commit"
            else
              # If there are changes to commit, make a commit
              git commit -m "Copied $dir to $branch"
            fi

            # Push the branch to the remote repository
             git push --force https://$PAT@github.com/boop-bap/JokeManagerMonoRepo.git $branch
          }

          # Call the function for each directory
          copy_to_branch 'API' $api_branch
          copy_to_branch 'BlazorApp' $blazorapp_branch
